# Generated by Django 2.0.6 on 2018-06-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('S', 'small / medium business'), ('E', 'enterprise'), ('O', 'organisation'), ('I', 'individual')], max_length=2, null=True)),
                ('user_business', models.CharField(blank=True, choices=[('M', 'Maker or manufacturer of physical products'), ('P', 'Ingredient or material producer'), ('R', 'Retailer'), ('A', 'Auditor')], max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
